# Generated by Django 3.1.7 on 2021-04-20 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emile', models.EmailField(max_length=254)),
                ('numpper', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=7)),
                ('place', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('book1', models.CharField(max_length=25)),
                ('book2', models.CharField(max_length=25)),
                ('book3', models.CharField(max_length=25)),
                ('book4', models.CharField(max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
