# Generated by Django 3.1.7 on 2021-04-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='fristName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='book1',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='book2',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='book3',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='book4',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
