# Generated by Django 3.1.7 on 2021-04-21 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_board', '0002_auto_20210421_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='gender',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='numpper',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='order_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raelName_order', models.CharField(max_length=25)),
                ('nummper_order', models.CharField(max_length=25)),
                ('place_order', models.CharField(max_length=25)),
                ('book1_order', models.CharField(blank=True, max_length=25)),
                ('book2_order', models.CharField(blank=True, max_length=25)),
                ('book3_order', models.CharField(blank=True, max_length=25)),
                ('book4_order', models.CharField(blank=True, max_length=25)),
                ('stats_order', models.CharField(default='Wating', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
