# Generated by Django 3.1.7 on 2021-05-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0007_auto_20210422_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
